# Generated by Django 4.2.3 on 2023-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('books', 'Books'), ('electronics', 'Electronics'), ('fruits', 'Fruits'), ('cars', 'Cars'), ('sports', 'Sports'), ('home', 'Home'), ('clothing', 'Clothing'), ('clothinga', 'Clothinga'), ('clothings', 'Clothings'), ('clothingc', 'Clothingc'), ('clothingd', 'Clothingd'), ('clothingf', 'Clothingf')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
